name: Download openssl-tool deb

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download openssl-tool for aarch64
        run: |
          wget https://packages.termux.org/apt/termux-main/pool/main/o/openssl-tool/openssl-tool_3.4.0-1_aarch64.deb
      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: openssl-tool-deb
          path: openssl-tool_*.deb
